CREATE DATABASE dbcrud;

CREATE TABLE IF NOT EXISTS `usuarios` (
`Name` VARCHAR(60) NULL,
`CPF` VARCHAR(60) PRIMARY KEY NOT NULL,
`PhoneNumber` VARCHAR (60) NULL,
`CelNumber` VARCHAR (60) NOT NULL,
`FaxNumber` VARCHAR (60) NULL,
`Email` VARCHAR(60) NULL,
`Cep` VARCHAR(60) NULL
);


